'**/galaxy-image-analysis/tools/rfove/rfove.xml':
  ignore:
    - GIA202  # using `.value` on input variables is discouraged

'**/galaxy-image-analysis/tools/superdsm/superdsm.xml':
  ignore:
    - GIA202  # using `.value` on input variables is discouraged

'**/galaxy-image-analysis/tools/2d_simple_filter/filter.xml':
  ignore:
    - GIA201  # bug in tool XML: `input.extension` should be `setup.input.extension`
    - GIA202  # bug in tool XML: `input.extension` should be `setup.input.extension`
