#'**/galaxy-image-analysis/tools/rfove/rfove.xml':
#  ignore:
#    - GIA202  # probably a bug in tool XML (check!)

'**/galaxy-image-analysis/tools/superdsm/superdsm.xml':
  ignore:
    - GIA202  # probably a bug in tool XML (check!)

'**/galaxy-image-analysis/tools/2d_simple_filter/filter.xml':
  ignore:
    - GIA201  # bug in tool XML: `input.extension` should be `setup.input.extension`
    - GIA202  # bug in tool XML: `input.extension` should be `setup.input.extension`
